In [28]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [4]:
iris_dataset = load_iris()

In [7]:
xtrain, xtest, ytrain, ytest = train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0)

In [18]:
kn = KNeighborsClassifier(n_neighbors=5)
kn.fit(xtrain,ytrain)

KNeighborsClassifier()

In [9]:
print("Target names:\n",iris_dataset.target_names)

Target names:
 ['setosa' 'versicolor' 'virginica']


In [12]:
for i in range(len(iris_dataset.target_names)):
  print("[{0}]:[{1}]".format(i,iris_dataset.target_names[i]))

[0]:[setosa]
[1]:[versicolor]
[2]:[virginica]


In [30]:
print("data:\n",iris_dataset["data"])
print("target:\n",iris_dataset["target"])
print("x train: \n",xtrain)
print("x test: \n",xtest)
print("y train: \n",ytrain)
print("y test: \n",ytest)

data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9

In [22]:
for i in range(len(xtest)):
  x = xtest[i]
  xnew = np.array([x])
  prediction = kn.predict(xnew)
  print("actual:{0} {1}  prediction:{2}:{3}".format(ytest[i],iris_dataset["target_names"][ytest[i]],prediction,iris_dataset["target_names"][prediction]))

actual:2 virginica  prediction:[2]:['virginica']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:0 setosa  prediction:[0]:['setosa']
actual:2 virginica  prediction:[2]:['virginica']
actual:0 setosa  prediction:[0]:['setosa']
actual:2 virginica  prediction:[2]:['virginica']
actual:0 setosa  prediction:[0]:['setosa']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:2 virginica  prediction:[2]:['virginica']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:0 setosa  prediction:[0]:['setosa']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:1 versicolor  prediction:[1]:['versicolor']
actual:0 setosa  prediction:[0]:['setosa']
actual:0 setosa  prediction:[0]:['setosa']
actual:2 virginica  prediction:[2]:[

In [27]:
print("Accuracy score: {:.2f}".format(kn.score(xtest,ytest)))

Accuracy score: 0.97
